### ISSUE TITLE
Best Result is not taken

### ISSUE THREAD

**Issue by walderT** [sourcebroker/imageopt#10]
I found a problem if the second iteration result gets the same bytes as the original image.

Look here:
https://github.com/sourcebroker/imageopt/blob/63a744fdd216fd16c0626503b325f48aaf018e39/Classes/Service/ImageManipulationService.php#L161-L162

The first condition mets in this case, because the
$theBestOptimizedImage is the empty tempfile defined in
`$theBestOptimizedImage = $this->createTempFile(); `
https://github.com/sourcebroker/imageopt/blob/63a744fdd216fd16c0626503b325f48aaf018e39/Classes/Service/ImageManipulationService.php#L152

**Comment by kszymukowicz** [comment]
Please check to 1.0.0 version released today as its complete rewrite and probably this problem is fixed there.

**Comment by kszymukowicz** [comment]
I am closing this issue because no response.
