### ISSUE TITLE
failed on delete images

### ISSUE THREAD

**Issue by maikusch** [sourcebroker/imageopt#3]
hey there,
i tried your ext to imageoptimization. Installation was easy. But if i run the optimization task, i always geht this error:

Execution of task "Extbase CommandController Task (extbase)" failed with the following message: PHP Warning: unlink(fileadmin/_processed_/c/b/csm_slider-stadtentwicklung_dd09009e70.jpg): No such file or directory in /homepages/28/d574274134/htdocs/update7/typo3conf/ext/imageopt/Classes/Service/ImageManipulationService.php line 220

but the files are really there! Do you have a hint for this problem?

**Comment by t33k** [comment]
hello

tnx - I will check that out on weekend.

**Comment by t33k** [comment]
Could you recheck plz ? 
There is version 0.3.0 now.
