### ISSUE TITLE
[FEATURE] Make persisting of $optimizationResult optional

### ISSUE THREAD

**Issue by frans-beech-it** [sourcebroker/imageopt#38]
Now the optimization result are always persisted. For bigger sites that means you get a table with a lot of records (> 1.000.000) that are mainly there for debug reasons.

Would it be possible to maken `$this->objectManager->get(OptimizationResultRepository::class)->add($optimizationResult);` optional?

**Comment by kszymukowicz** [comment]
Yes. You right. I will update that in next major release.

**Comment by kszymukowicz** [comment]
Added in version 5.0.0

```
tx_imageopt {
    log {
        enable = 0
    }
}
```

**Comment by fsaris** [comment]
Tnx!

**Comment by fsaris** [comment]
Feature is added in https://github.com/sourcebroker/imageopt/commit/4097bba2f69f29a6dd2262b7bdddea52ce224ab7 correct?

**Comment by kszymukowicz** [comment]
Yes, but mind that there was big refactoring between 4.0.0 and 5.0.0.
